PUT http://localhost:3003/api/blogs/5c6aaf47658bfa10a3d52e82
content-type: application/json

{
  "user": "5c6aad23533f3e0fd4167c8c",
  "likes": 4,
  "author": "Jeesus Itse",
  "title": "Blogit on tärkeitä vol 3",
  "url": "www.reddit.com"
}